### PR TITLE
feat: Screenshot Schedule / Timetable / Calendar

### PR DESCRIPTION
**Pull request by FlyteWizard**
# Description

**Proposal**: Allow users to screenshot the schedule/timetable/calendar. As a user I want a simple way to screenshot the schedule/timetable/calendar so I can share with friends and keep it on my device or to print out.

**Discussion Points**:

- [x] Location of Button
- [x] Icon of Button
- [x] Colour of Button
- [x] Language of Button

## Screenshots

**Inspiration**:

inspiration-courseup-screenshot-feature

**Proposal**:

202209_calendar_proposal

### Before

Capture d’écran, le 2022-06-06 à 08 28 55

Capture d’écran, le 2022-06-06 à 08 29 48

### After

Capture d’écran, le 2022-06-06 à 08 30 49

Capture d’écran, le 2022-06-06 à 08 31 03

## Checklist

- [x] The code follows all style guidelines.
- [x] The code passes all required tests.
- [x] The code is documented.
- [ ] The code includes tests.
- [x] I have self-reviewed my changes and have done QA.

## General Comments

[https://html2canvas.hertzen.com](https://html2canvas.hertzen.com) is the package added to aid/perform the screenshot.

The PR also fixes some minor errors that were present within the component.

**Notably**:

- `Error reading localStorage key “user:saved_courses”:`

Capture d’écran, le 2022-06-06 à 08 33 01

### CODE REVIEW

**Comment by FlyteWizard** [comment]
Capture d’écran, le 2022-06-06 à 23 08 24
Capture d’écran, le 2022-06-06 à 23 08 33
Capture d’écran, le 2022-06-06 à 23 08 55
Capture d’écran, le 2022-06-06 à 23 08 44

**Comment by FlyteWizard** [comment]
## Footer Proposal

202209_calendar_dark_screenshot_footer_proposal_desktop
202209_calendar_light_screenshot_footer_proposal_desktop
202209_calendar_light_screenshot_footer_proposal_mobile
202209_calendar_dark_screenshot_footer_proposal_mobile

**Comment by aomi** [comment]
@FlyteWizard footer looks overall good!
Implementation wise, I think including the shared timetable link `courseup.ca/s/XYZ` would be good (can probably omit the `https://`)

**Comment by aomi** [comment]
The application crashes when I try to navigate to the timetable page on the preview build.

**Comment by FlyteWizard** [comment]
```
TypeError: A.sort is not a function. (In 'A.sort((function(e,t){return e.subject>t.subject?1:-1}))', 'A.sort' is undefined)
(fonction anonyme) — Courses.tsx:130
Fa — react-dom.production.min.js:168:377
xM — Courses.tsx:130
sa — react-dom.production.min.js:157:139
Ka — react-dom.production.min.js:180:157
UA — react-dom.production.min.js:250:350
kA — react-dom.production.min.js:250:281
SA — react-dom.production.min.js:250:138
yA — react-dom.production.min.js:243:166
yA
(fonction anonyme) — react-dom.production.min.js:123:115
(fonction anonyme) — scheduler.production.min.js:18:343
Xo — react-dom.production.min.js:123
Yo — react-dom.production.min.js:122:428
hA — react-dom.production.min.js:237:203
Ta — react-dom.production.min.js:170:411
Ta
(fonction anonyme) — useGet.tsx:207
promiseReactionJob
```

**Comment by FlyteWizard** [comment]
202301_calendar

**Comment by aomi** [comment]
@FlyteWizard
202205_calendar(2)
Do you know why the text within each course event is shifted down a bit?

**Comment by FlyteWizard** [comment]
@aomi A solution could be having a modal with the canvas preview?

https://user-images.githubusercontent.com/10472448/173969681-2e7603e3-6332-4bc8-9434-7d3b2632b6f2.mov

And the reason the text shifts a bit for the course name and number has to do with bottom padding not being respected when switching to canvas. (I'll see if there is a suitable fix 😄 ).

**Comment by FlyteWizard** [comment]
screenshot_feature_desktop_dark_modal
screenshot_feature_desktop_dark_timetable
screenshot_feature_desktop_light_modal
screenshot_feature_desktop_light_timetable
screenshot_feature_mobile_dark_modal
screenshot_feature_mobile_dark_timetable
screenshot_feature_mobile_light_modal
screenshot_feature_mobile_light_timetable

---

202209_calendar_desktop_light
202209_calendar_desktop-dark
202209_calendar_mobile_light
202209_calendar_mobile-dark

**Review by aomi — APPROVED** [review]
LGTM. There's some changes I think we'd like to see mostly within the UI of the modal but its not worth blocking the initial release. We'll make some issues to address them later on.

**Comment by FlyteWizard** [comment]
@aomi Sounds good 👍 Feel free to send the mock-ups for the UI in this PR, or create an issue, or send them in Discord. 

Happy to make any modifications to better fit CourseUp. 😁

**Pull request merged**
